# Generated by Django 2.0.4 on 2018-04-15 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=12)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.Job')),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='about',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AddField(
            model_name='application',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.Student'),
        ),
    ]
