# Generated by Django 2.0.4 on 2018-04-15 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0002_auto_20180415_1452'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('student_id', 'job_id')},
        ),
    ]
