# Generated by Django 2.0.4 on 2018-04-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0003_auto_20180415_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='pos',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('pos', 'company')},
        ),
    ]
