# Generated by Django 2.0.4 on 2018-04-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0004_auto_20180415_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.CharField(default='undergrad', max_length=264),
            preserve_default=False,
        ),
    ]
