# Generated by Django 2.0.4 on 2018-04-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0005_job_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='jjjj', max_length=128),
            preserve_default=False,
        ),
    ]
