# Generated by Django 2.0.4 on 2018-04-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0006_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(default='llll', max_length=128),
            preserve_default=False,
        ),
    ]
