# Generated by Django 2.0.4 on 2018-04-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0007_company_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.CharField(default='a', max_length=128),
            preserve_default=False,
        ),
    ]
